use_frameworks!

target 'CSHBase_Example' do
  pod 'CSHBase', :path => '../'

  target 'CSHBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
